accounts/urls.py
from django.urls import path

from django.contrib.auth.views import LogoutView

from accounts.views import (
    RegisterView, LoginUserView,
    UserProfileView, UserListView,
    UserUpdateView, UserPasswordChangeView
)

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', RegisterView.as_view(), name='create'),
    path('profile/<int:pk>', UserProfileView.as_view(), name='user_profile'),
    path('users/', UserListView.as_view(), name='user_list'),
    path('user/update', UserUpdateView.as_view(), name='user_update'),
    path('user/password/change', UserPasswordChangeView.as_view(), name='user_password_change'),
]

api/urls.py
from django.urls import path

from api.views import ProjectApiView, IssueApiView

urlpatterns = [
    path('projects/<int:pk>', ProjectApiView.as_view()),
    path('issues/<int:pk>', IssueApiView.as_view()),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
    path('', include('issue_tracker.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

issue_tracker/urls.py
from django.urls import path

from issue_tracker.views import (
    IssueListView, DetailIssueView,
    IssueEditView, DeleteIssueView, IssueCreateView
)
from issue_tracker.views.project_views import (
    ProjectListView, ProjectView, ProjectCreateView,
    ProjectIssueCreateView, ProjectEditView, ProjectDeleteView, ProjectUsersUpdateView)

app_name = 'issue_tracker'

issue_urls = [
    path('issues/', IssueListView.as_view(), name='issue_list'),
    path('issue/create/', IssueCreateView.as_view(), name='create_issue'),
    path('issue/<int:pk>', DetailIssueView.as_view(), name='detail_issue'),
    path('issue/edit/<int:pk>', IssueEditView.as_view(), name='edit_issue'),
    path('issue/delete/<int:pk>', DeleteIssueView.as_view(), name='delete_issue'),
]

project_urls = [
    path('', ProjectListView.as_view(), name='project_list'),
    path('project/<int:pk>', ProjectView.as_view(), name='project_detail'),
    path('project/create/', ProjectCreateView.as_view(), name='project_create'),
    path('project/<int:pk>/edit/', ProjectEditView.as_view(), name='project_edit'),
    path('project/<int:pk>/users/edit/', ProjectUsersUpdateView.as_view(), name='project_users_update'),
    path('project/<int:pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),
    path('project/<int:pk>/issue/create/', ProjectIssueCreateView.as_view(), name='project_issue_create'),
]

urlpatterns = issue_urls + project_urls

issue_tracker/forms.py
from django import forms

from issue_tracker.models import Issue, Project


class ProjectModelForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'description', 'start_date', 'end_date']


class ProjectUsersModelForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['users']


class IssueModelForm(forms.ModelForm):
    class Meta:
        model = Issue
        fields = ['project', 'summary', 'description', 'status', 'type']


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label="Search")

issue_tracker/views.py
from urllib.parse import urlencode

from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.generic import TemplateView, FormView, ListView
from issue_tracker.forms import IssueModelForm, SimpleSearchForm
from issue_tracker.models import Issue


class IndexView(ListView):
    template_name = 'issue/index.html'
    context_object_name = 'issues'
    model = Issue
    paginate_by = 5
    allow_empty = False

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        try:
            return super().get(request, *args, **kwargs)
        except Http404:
            context = {
                '404_error': 'Oops something went wrong!',
                'form': self.form
            }
            if self.search_value:
                context['query'] = urlencode({'search': self.search_value})
            return render(request, 'issue/index.html', context=context)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class IssueCreateView(FormView):
    template_name = 'issue/create_issue.html'
    form_class = IssueModelForm

    def form_valid(self, form):
        summary = form.cleaned_data['summary']
        description = form.cleaned_data['description']
        status = form.cleaned_data['status']
        types = form.cleaned_data['type']
        self.issue = Issue.objects.create(
            summary=summary,
            description=description,
            status=status
        )
        self.issue.type.set(types)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('detail_issue', kwargs={'pk': self.issue.pk})


class DetailIssueView(TemplateView):
    template_name = 'issue/issue_template.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['issue'] = get_object_or_404(Issue, pk=kwargs['pk'])
        return context


class IssueEditView(FormView):
    template_name = 'issue/edit_issue.html'
    form_class = IssueModelForm

    def dispatch(self, request, *args, **kwargs):
        self.issue = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['issue'] = self.issue
        return context

    def get_initial(self):
        initial = {}
        for key in 'summary', 'description', 'status':
            initial[key] = getattr(self.issue, key)
        initial['type'] = self.issue.type.all()
        return initial

    def form_valid(self, form):
        types = form.cleaned_data.pop('type')
        for key, value in form.cleaned_data.items():
            if value is not None:
                setattr(self.issue, key, value)
        self.issue.save()
        self.issue.type.set(types)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('detail_issue', kwargs={'pk': self.issue.pk})

    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Issue, pk=pk)


class DeleteIssueView(TemplateView):
    def post(self, request, *args, **kwargs):
        issue = get_object_or_404(Issue, pk=kwargs['pk'])
        issue.delete()
        return redirect('index')

issue_tracker/views/issue_views.py
from urllib.parse import urlencode

from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.generic import TemplateView, ListView, DeleteView, UpdateView, CreateView
from django.contrib.auth.mixins import PermissionRequiredMixin

from issue_tracker.forms import IssueModelForm, SimpleSearchForm
from issue_tracker.models import Issue


class IssueListView(ListView):
    template_name = 'issue/issue_list.html'
    context_object_name = 'issues'
    model = Issue
    paginate_by = 5
    allow_empty = False

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        try:
            return super().get(request, *args, **kwargs)
        except Http404:
            context = {
                '404_error': 'Oops something went wrong!',
                'form': self.form
            }
            if self.search_value:
                context['query'] = urlencode({'search': self.search_value})
            return render(request, 'issue/issue_list.html', context=context)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class IssueCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'issue/create_issue.html'
    form_class = IssueModelForm
    permission_required = 'issue_tracker.add_issue'

    def has_permission(self):
        return self.request.user.is_superuser

    def get_success_url(self):
        return reverse('issue_tracker:detail_issue', kwargs={'pk': self.object.pk})


class DetailIssueView(TemplateView):
    template_name = 'issue/issue_template.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['issue'] = get_object_or_404(Issue, pk=kwargs['pk'])
        return context


class IssueEditView(PermissionRequiredMixin, UpdateView):
    template_name = 'issue/edit_issue.html'
    model = Issue
    form_class = IssueModelForm
    context_object_name = 'issue'
    permission_required = 'issue_tracker.change_issue'

    def has_permission(self):
        issue = get_object_or_404(Issue, pk=self.kwargs.get('pk'))
        project = issue.project
        return (
                (super().has_permission() and (self.request.user in project.users.all())) or
                self.request.user.is_superuser
        )

    def get_success_url(self):
        return reverse('issue_tracker:detail_issue', kwargs={'pk': self.object.pk})


class DeleteIssueView(PermissionRequiredMixin, DeleteView):
    template_name = 'issue/issue_template.html'
    model = Issue
    permission_required = 'issue_tracker.delete_issue'

    def has_permission(self):
        issue = get_object_or_404(Issue, pk=self.kwargs.get('pk'))
        project = issue.project
        return (
                (super().has_permission() and (self.request.user in project.users.all())) or
                self.request.user.is_superuser
        )

    def get_success_url(self):
        return reverse('issue_tracker:project_detail', kwargs={'pk': self.object.project.pk})

issue_tracker/views/project_views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin

from issue_tracker.forms import ProjectModelForm, IssueModelForm, ProjectUsersModelForm
from issue_tracker.models import Project, Issue


class ProjectListView(ListView):
    template_name = 'project/project_list.html'
    model = Project
    context_object_name = 'projects'


class ProjectView(DetailView):
    template_name = 'project/project_detail.html'
    model = Project
    context_object_name = 'project'


class ProjectCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'project/project_create.html'
    model = Project
    form_class = ProjectModelForm
    permission_required = 'issue_tracker.add_project'

    def form_valid(self, form):
        self.object = form.save()
        self.object.users.add(self.request.user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse('issue_tracker:project_detail', kwargs={'pk': self.object.pk})


class ProjectUsersUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'project/project_users_update.html'
    model = Project
    form_class = ProjectUsersModelForm
    context_object_name = 'project'
    permission_required = 'issue_tracker.change_project_users'

    def has_permission(self):
        return (
                (super().has_permission() and (self.request.user in self.get_object().users.all())) or
                self.request.user.is_superuser
        )

    def get_success_url(self):
        return reverse('issue_tracker:project_detail', kwargs={'pk': self.object.pk})


class ProjectIssueCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'project/project_issue_create.html'
    model = Issue
    form_class = IssueModelForm
    permission_required = 'issue_tracker.add_issue'

    def has_permission(self):
        project = get_object_or_404(Project, pk=self.kwargs.get('pk'))
        return (
                (super().has_permission() and (self.request.user in project.users.all())) or
                self.request.user.is_superuser
        )

    def form_valid(self, form):
        project = get_object_or_404(Project, pk=self.kwargs.get('pk'))
        issue = form.save(commit=False)
        issue.project = project
        issue.save()
        return redirect('issue_tracker:project_detail', pk=project.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['project'] = get_object_or_404(Project, pk=self.kwargs['pk'])
        return context


class ProjectEditView(PermissionRequiredMixin, UpdateView):
    template_name = 'project/project_edit.html'
    model = Project
    form_class = ProjectModelForm
    context_object_name = 'project'
    permission_required = 'issue_tracker.change_project'

    def get_success_url(self):
        return reverse('issue_tracker:project_detail', kwargs={'pk': self.object.pk})


class ProjectDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'project/project_detail.html'
    model = Project
    success_url = reverse_lazy('issue_tracker:project_list')
    context_object_name = ''
    permission_required = 'issue_tracker.delete_project'

issue_tracker/templates/partial/common/delete_modal.html
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete confirmation</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure to remove issue #{{ issue.pk }}?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-dark" data-bs-dismiss="modal">Close</button>
        <form action="{% url 'issue_tracker:delete_issue' issue.pk %}" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>

issue_tracker/templates/partial/common/delete_project_modal.html
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete confirmation</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure to remove project #{{ project.pk }}?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-dark" data-bs-dismiss="modal">Close</button>
        <form action="{% url 'issue_tracker:project_delete' project.pk %}" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>

issue_tracker/templates/partial/common/issue_form.html
{% csrf_token %}
<div class="mb-3">
    <label for="title" class="form-label">{{ form.summary.label }}</label>
    <input type="text" class="form-control" id="title" name="{{ form.summary.name }}" value="{{ issue.summary }}">
</div>
<div class="mb-3">
    <label for="description" class="form-label">{{ form.description.label }}</label>
    <textarea name="{{ form.description.name }}" class="form-control" id="description"
              rows="3">{{ issue.description|default_if_none:'' }}</textarea>
</div>
<div class="mb-3">
    <label for="project" class="form-label">{{ form.project.label }}</label>
    <select name="{{ form.project.name }}" class="form-select" aria-label="Default select example">
        {% for choice in form.project.field.queryset %}
            {% if choice.pk == issue.project.pk %}
                <option value="{{ choice.pk }}" selected>{{ choice.title }}</option>
            {% else %}
                <option value="{{ choice.pk }}">{{ choice.title }}</option>
            {% endif %}
        {% endfor %}
    </select>
</div>
<div class="mb-3">
    <label for="status" class="form-label">{{ form.status.label }}</label>
    <select name="{{ form.status.name }}" class="form-select" aria-label="Default select example">
        {% for choice in form.status.field.queryset %}
            {% if choice.pk == issue.status.pk %}
                <option value="{{ choice.pk }}" selected>{{ choice.title }}</option>
            {% else %}
                <option value="{{ choice.pk }}">{{ choice.title }}</option>
            {% endif %}
        {% endfor %}
    </select>
</div>
<div class="mb-3">
    <label for="type" class="form-label">{{ form.type.label }}</label>
    <select multiple name="{{ form.type.name }}" class="form-select" aria-label="Default select example">
        {% for choice in form.type.field.queryset %}
            {% if choice in issue.type.all %}
                <option value="{{ choice.pk }}" selected>{{ choice.title }}</option>
            {% else %}
                <option value="{{ choice.pk }}">{{ choice.title }}</option>
            {% endif %}
        {% endfor %}
    </select>
</div>
<button type="submit" class="btn btn-dark">{{ btn_title }}</button>

issue_tracker/templates/partial/common/menu.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'issue_tracker:project_list' %}">Projects</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'issue_tracker:issue_list' %}">Issues</a>
                </li>
            {% if perms.auth.view_user %}
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'accounts:user_list' %}">Users</a>
            </li>
            {% endif %}
                {% if perms.issue_tracker.add_project %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'issue_tracker:project_create' %}">Create
                            project</a>
                    </li>
                {% endif %}
                {% if request.user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'issue_tracker:create_issue' %}">Create
                            issue</a>
                    </li>
                {% endif %}
                {% if request.user.is_authenticated %}
                    <li class="nav-item nav-link">
                        Hello, <a href="{% url 'accounts:user_profile' user.pk %}">{{ user.get_full_name }}</a>!
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page"
                           href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}">Sign out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="
                                {% url 'accounts:login' %}{% if register_page or login_page %}{% else %}?next={{ request.get_full_path }}{% endif %}">Sign
                            in</a>
                    </li>
            {% endif %}
        </ul>
        <form class="d-flex" action="{% url 'issue_tracker:issue_list' %}" method="GET">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="{{ search_form.search.name }}" value="{{ search_form.search.value|default_if_none:'' }}">
            <button class="btn btn-dark" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

issue_tracker/templates/partial/common/paginator.html
<div class="pagination">
    <span class="step-links">
        <a href="?{% if query %}{{ query }}&{% endif %}page=1">First</a>
        {% if page_obj.has_previous %}
            <a href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.previous_page_number }}">Back</a>
        {% else %}
            <span class="page-disabled">Back</span>
        {% endif %}
        <form class="current-page" method="get">
            <label for="page">
                Page <input type="text" name="page" id="page" value="{{ page_obj.number }}">
                of {{ page_obj.paginator.num_pages }}
            </label>
        </form>
        {% if page_obj.has_next %}
            <a href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.next_page_number }}">Next</a>
        {% else %}
            <span class="page-disabled">Next</span>
        {% endif %}
        <a href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.paginator.num_pages }}">Last</a>
    </span>
</div>

issue_tracker/templates/partial/common/project_form.html
{% csrf_token %}
<div class="mb-3">
    <label for="title" class="form-label">{{ form.title.label }}</label>
    <input type="text" class="form-control" id="title" name="{{ form.title.name }}" value="{{ form.instance.title }}">
</div>
<div class="mb-3">
    <label for="description" class="form-label">{{ form.description.label }}</label>
    <textarea name="{{ form.description.name }}" class="form-control" id="description"
              rows="3">{{ form.instance.description|default_if_none:'' }}</textarea>
</div>
<div class="mb-3">
    <label for="start_date" class="form-label">{{ form.start_date.label }}</label>
    <input type="date" class="form-control" id="start_date" name="{{ form.start_date.name }}" value="{{ form.instance.start_date|date:'Y-m-d' }}">
</div>
<div class="mb-3">
    <label for="end_date" class="form-label">{{ form.end_date.label }}</label>
    <input type="date" class="form-control" id="end_date" name="{{ form.end_date.name }}" value="{{ form.instance.end_date|date:'Y-m-d' }}">
</div>
<button type="submit" class="btn btn-dark">{{ btn_title }}</button>

issue_tracker/templates/partial/common/project_issue_form.html
{% csrf_token %}
<div class="mb-3">
    <label for="title" class="form-label">{{ form.summary.label }}</label>
    <input type="text" class="form-control" id="title" name="{{ form.summary.name }}" value="{{ issue.summary }}">
</div>
<div class="mb-3">
    <input type="hidden" id="project" name="{{ form.project.name }}" value="{{ project.pk }}">
</div>
<div class="mb-3">
    <label for="description" class="form-label">{{ form.description.label }}</label>
    <textarea name="{{ form.description.name }}" class="form-control" id="description"
              rows="3">{{ issue.description|default_if_none:'' }}</textarea>
</div>
<div class="mb-3">
    <label for="status" class="form-label">{{ form.status.label }}</label>
    <select name="{{ form.status.name }}" class="form-select" aria-label="Default select example">
        {% for choice in form.status.field.queryset %}
            {% if choice.pk == issue.status.pk %}
                <option value="{{ choice.pk }}" selected>{{ choice.title }}</option>
            {% else %}
                <option value="{{ choice.pk }}">{{ choice.title }}</option>
            {% endif %}
        {% endfor %}
    </select>
</div>
<div class="mb-3">
    <label for="type" class="form-label">{{ form.type.label }}</label>
    <select multiple name="{{ form.type.name }}" class="form-select" aria-label="Default select example">
        {% for choice in form.type.field.queryset %}
            {% if choice in issue.type.all %}
                <option value="{{ choice.pk }}" selected>{{ choice.title }}</option>
            {% else %}
                <option value="{{ choice.pk }}">{{ choice.title }}</option>
            {% endif %}
        {% endfor %}
    </select>
</div>
<button type="submit" class="btn btn-dark">{{ btn_title }}</button>