api/urls.py
from django.urls import path

from api.views import ProjectApiView, IssueApiView

urlpatterns = [
    path('projects/<int:pk>', ProjectApiView.as_view()),
    path('issues/<int:pk>', IssueApiView.as_view()),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
    path('', include('issue_tracker.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

issue_tracker/urls.py
from django.urls import path

from issue_tracker.views import (
    IssueListView, DetailIssueView,
    IssueEditView, DeleteIssueView, IssueCreateView
)
from issue_tracker.views.project_views import (
    ProjectListView, ProjectView, ProjectCreateView,
    ProjectIssueCreateView, ProjectEditView, ProjectDeleteView, ProjectUsersUpdateView)

app_name = 'issue_tracker'

issue_urls = [
    path('issues/', IssueListView.as_view(), name='issue_list'),
    path('issue/create/', IssueCreateView.as_view(), name='create_issue'),
    path('issue/<int:pk>', DetailIssueView.as_view(), name='detail_issue'),
    path('issue/edit/<int:pk>', IssueEditView.as_view(), name='edit_issue'),
    path('issue/delete/<int:pk>', DeleteIssueView.as_view(), name='delete_issue'),
]

project_urls = [
    path('', ProjectListView.as_view(), name='project_list'),
    path('project/<int:pk>', ProjectView.as_view(), name='project_detail'),
    path('project/create/', ProjectCreateView.as_view(), name='project_create'),
    path('project/<int:pk>/edit/', ProjectEditView.as_view(), name='project_edit'),
    path('project/<int:pk>/users/edit/', ProjectUsersUpdateView.as_view(), name='project_users_update'),
    path('project/<int:pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),
    path('project/<int:pk>/issue/create/', ProjectIssueCreateView.as_view(), name='project_issue_create'),
]

urlpatterns = issue_urls + project_urls

issue_tracker/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.deletion import get_candidate_relations_to_delete

from issue_tracker.validators import MinLengthValidator


class SoftDeletedManager(models.Manager):
    def get_queryset(self):
        return super(SoftDeletedManager, self).get_queryset().filter(is_deleted=False)


class IsDeletedMixin(models.Model):
    is_deleted = models.BooleanField(default=False)
    objects = SoftDeletedManager()

    def delete(self, using=None, keep_parents=False):
        self.is_deleted = True
        delete_candidates = get_candidate_relations_to_delete(self.__class__._meta)
        if delete_candidates:
            for relation in delete_candidates:
                if (
                        relation.on_delete.__name__ == 'CASCADE'
                        and relation.one_to_many
                        and not relation.hidden
                ):
                    for item in getattr(self, relation.related_name).all():
                        item.delete()

        self.save(update_fields=['is_deleted', ])

    class Meta:
        abstract = True


class Project(IsDeletedMixin):
    users = models.ManyToManyField(get_user_model(), related_name='projects', verbose_name='Users')
    title = models.CharField(max_length=100, verbose_name='Title', validators=(MinLengthValidator(3),))
    description = models.TextField(
        max_length=800,
        null=True,
        blank=True,
        verbose_name='Description',
        validators=(MinLengthValidator(3),)
    )
    start_date = models.DateField(verbose_name='Start date')
    end_date = models.DateField(null=True, blank=True, verbose_name='End date')

    def __str__(self):
        return "{}. {}".format(self.pk, self.title)

    class Meta:
        permissions = [('change_project_users', 'Can change users of a project')]


class Issue(IsDeletedMixin):
    project = models.ForeignKey(
        to='issue_tracker.Project',
        related_name='issues',
        on_delete=models.CASCADE,
        verbose_name='Project',
        null=True
    )
    summary = models.CharField(max_length=500, verbose_name='Summary', validators=(MinLengthValidator(3),))
    description = models.TextField(
        max_length=2500,
        null=True,
        blank=True,
        verbose_name='Description',
        validators=(MinLengthValidator(3),)
    )
    status = models.ForeignKey('issue_tracker.Status', on_delete=models.CASCADE, verbose_name='Status')
    type = models.ManyToManyField('issue_tracker.Type', related_name='issues', verbose_name='Type')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Updated')

    def __str__(self):
        return "{}. {}".format(self.pk, self.summary)


class Status(IsDeletedMixin):
    title = models.CharField(max_length=50, verbose_name='Title')

    def __str__(self):
        return "{}. {}".format(self.pk, self.title)


class Type(IsDeletedMixin):
    title = models.CharField(max_length=100, verbose_name='Title')

    def __str__(self):
        return "{}. {}".format(self.pk, self.title)

issue_tracker/forms.py
from django import forms

from issue_tracker.models import Issue, Project


class ProjectModelForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'description', 'start_date', 'end_date']


class ProjectUsersModelForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['users']


class IssueModelForm(forms.ModelForm):
    class Meta:
        model = Issue
        fields = ['project', 'summary', 'description', 'status', 'type']


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label="Search")

issue_tracker/views.py
from urllib.parse import urlencode

from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.generic import TemplateView, FormView, ListView
from issue_tracker.forms import IssueModelForm, SimpleSearchForm
from issue_tracker.models import Issue


class IndexView(ListView):
    template_name = 'issue/index.html'
    context_object_name = 'issues'
    model = Issue
    paginate_by = 5
    allow_empty = False

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        try:
            return super().get(request, *args, **kwargs)
        except Http404:
            context = {
                '404_error': 'Oops something went wrong!',
                'form': self.form
            }
            if self.search_value:
                context['query'] = urlencode({'search': self.search_value})
            return render(request, 'issue/index.html', context=context)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class IssueCreateView(FormView):
    template_name = 'issue/create_issue.html'
    form_class = IssueModelForm

    def form_valid(self, form):
        summary = form.cleaned_data['summary']
        description = form.cleaned_data['description']
        status = form.cleaned_data['status']
        types = form.cleaned_data['type']
        self.issue = Issue.objects.create(
            summary=summary,
            description=description,
            status=status
        )
        self.issue.type.set(types)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('detail_issue', kwargs={'pk': self.issue.pk})


class DetailIssueView(TemplateView):
    template_name = 'issue/issue_template.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['issue'] = get_object_or_404(Issue, pk=kwargs['pk'])
        return context


class IssueEditView(FormView):
    template_name = 'issue/edit_issue.html'
    form_class = IssueModelForm

    def dispatch(self, request, *args, **kwargs):
        self.issue = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['issue'] = self.issue
        return context

    def get_initial(self):
        initial = {}
        for key in 'summary', 'description', 'status':
            initial[key] = getattr(self.issue, key)
        initial['type'] = self.issue.type.all()
        return initial

    def form_valid(self, form):
        types = form.cleaned_data.pop('type')
        for key, value in form.cleaned_data.items():
            if value is not None:
                setattr(self.issue, key, value)
        self.issue.save()
        self.issue.type.set(types)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('detail_issue', kwargs={'pk': self.issue.pk})

    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Issue, pk=pk)


class DeleteIssueView(TemplateView):
    def post(self, request, *args, **kwargs):
        issue = get_object_or_404(Issue, pk=kwargs['pk'])
        issue.delete()
        return redirect('index')

issue_tracker/views/issue_views.py
from urllib.parse import urlencode

from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.generic import TemplateView, ListView, DeleteView, UpdateView, CreateView
from django.contrib.auth.mixins import PermissionRequiredMixin

from issue_tracker.forms import IssueModelForm, SimpleSearchForm
from issue_tracker.models import Issue


class IssueListView(ListView):
    template_name = 'issue/issue_list.html'
    context_object_name = 'issues'
    model = Issue
    paginate_by = 5
    allow_empty = False

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        try:
            return super().get(request, *args, **kwargs)
        except Http404:
            context = {
                '404_error': 'Oops something went wrong!',
                'form': self.form
            }
            if self.search_value:
                context['query'] = urlencode({'search': self.search_value})
            return render(request, 'issue/issue_list.html', context=context)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class IssueCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'issue/create_issue.html'
    form_class = IssueModelForm
    permission_required = 'issue_tracker.add_issue'

    def has_permission(self):
        return self.request.user.is_superuser

    def get_success_url(self):
        return reverse('issue_tracker:detail_issue', kwargs={'pk': self.object.pk})


class DetailIssueView(TemplateView):
    template_name = 'issue/issue_template.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['issue'] = get_object_or_404(Issue, pk=kwargs['pk'])
        return context


class IssueEditView(PermissionRequiredMixin, UpdateView):
    template_name = 'issue/edit_issue.html'
    model = Issue
    form_class = IssueModelForm
    context_object_name = 'issue'
    permission_required = 'issue_tracker.change_issue'

    def has_permission(self):
        issue = get_object_or_404(Issue, pk=self.kwargs.get('pk'))
        project = issue.project
        return (
                (super().has_permission() and (self.request.user in project.users.all())) or
                self.request.user.is_superuser
        )

    def get_success_url(self):
        return reverse('issue_tracker:detail_issue', kwargs={'pk': self.object.pk})


class DeleteIssueView(PermissionRequiredMixin, DeleteView):
    template_name = 'issue/issue_template.html'
    model = Issue
    permission_required = 'issue_tracker.delete_issue'

    def has_permission(self):
        issue = get_object_or_404(Issue, pk=self.kwargs.get('pk'))
        project = issue.project
        return (
                (super().has_permission() and (self.request.user in project.users.all())) or
                self.request.user.is_superuser
        )

    def get_success_url(self):
        return reverse('issue_tracker:project_detail', kwargs={'pk': self.object.project.pk})

issue_tracker/views/project_views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin

from issue_tracker.forms import ProjectModelForm, IssueModelForm, ProjectUsersModelForm
from issue_tracker.models import Project, Issue


class ProjectListView(ListView):
    template_name = 'project/project_list.html'
    model = Project
    context_object_name = 'projects'


class ProjectView(DetailView):
    template_name = 'project/project_detail.html'
    model = Project
    context_object_name = 'project'


class ProjectCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'project/project_create.html'
    model = Project
    form_class = ProjectModelForm
    permission_required = 'issue_tracker.add_project'

    def form_valid(self, form):
        self.object = form.save()
        self.object.users.add(self.request.user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse('issue_tracker:project_detail', kwargs={'pk': self.object.pk})


class ProjectUsersUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'project/project_users_update.html'
    model = Project
    form_class = ProjectUsersModelForm
    context_object_name = 'project'
    permission_required = 'issue_tracker.change_project_users'

    def has_permission(self):
        return (
                (super().has_permission() and (self.request.user in self.get_object().users.all())) or
                self.request.user.is_superuser
        )

    def get_success_url(self):
        return reverse('issue_tracker:project_detail', kwargs={'pk': self.object.pk})


class ProjectIssueCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'project/project_issue_create.html'
    model = Issue
    form_class = IssueModelForm
    permission_required = 'issue_tracker.add_issue'

    def has_permission(self):
        project = get_object_or_404(Project, pk=self.kwargs.get('pk'))
        return (
                (super().has_permission() and (self.request.user in project.users.all())) or
                self.request.user.is_superuser
        )

    def form_valid(self, form):
        project = get_object_or_404(Project, pk=self.kwargs.get('pk'))
        issue = form.save(commit=False)
        issue.project = project
        issue.save()
        return redirect('issue_tracker:project_detail', pk=project.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['project'] = get_object_or_404(Project, pk=self.kwargs['pk'])
        return context


class ProjectEditView(PermissionRequiredMixin, UpdateView):
    template_name = 'project/project_edit.html'
    model = Project
    form_class = ProjectModelForm
    context_object_name = 'project'
    permission_required = 'issue_tracker.change_project'

    def get_success_url(self):
        return reverse('issue_tracker:project_detail', kwargs={'pk': self.object.pk})


class ProjectDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'project/project_detail.html'
    model = Project
    success_url = reverse_lazy('issue_tracker:project_list')
    context_object_name = ''
    permission_required = 'issue_tracker.delete_project'

issue_tracker/templates/issue/create_issue.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Create issue</h1>
<form action="{% url 'issue_tracker:create_issue' %}" method="post">
  {% include 'partial/common/issue_form.html' with btn_title='Create' %}
  </form>
{% endblock %}

issue_tracker/templates/issue/edit_issue.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Edit issue #{{ issue.pk }}</h1>
<form action="{% url 'issue_tracker:edit_issue' issue.pk %}" method="post">
  {% include 'partial/common/issue_form.html' with btn_title='Edit' %}
  </form>
{% endblock %}

issue_tracker/templates/issue/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Issues</h1>
{% for issue in issues %}
<div class="card mb-3">
  <div class="row g-0">
      <div class="col-md-8">
          <div class="card-body">
              <h5 class="card-title"><a href="{% url 'detail_issue' issue.pk %}"> {{ issue.summary }}</a></h5>
              <p class="card-text"><small class="text-muted">#{{ issue.pk }} Created at {{ issue.created_at }}</small></p>
              <p class="card-text"><small class="text-muted">{% for type in issue.type.all %}
          {% if type == issue.type.last %}
              {{ type.title }}
          {% else %}
              {{ type.title }},
          {% endif %}
      {% endfor %}</small></p>
          </div>
      </div>
      <div class="col-md-4">
          <div class="card-body">
              <h5 class="card-title">{{ issue.status.title }}</h5>
              <p class="card-text"><small class="text-muted">Updated at {{ issue.updated_at }}</small></p>
          </div>
      </div>
  </div>
</div>
{% empty %}
    <h3>404: {{ 404_error }}</h3>
    <h3>Issues not found</h3>
{% endfor %}
{% endblock %}

issue_tracker/templates/issue/issue_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% if request.user.is_authenticated %}
        <h1>Issues</h1>
        {% for issue in issues %}
            <div class="card mb-3">
                <div class="row g-0">
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title"><a
                                    href="{% url 'issue_tracker:detail_issue' issue.pk %}"> {{ issue.summary }}</a></h5>
                            <p class="card-text"><small class="text-muted">#{{ issue.pk }} Created
                                at {{ issue.created_at }}</small></p>
                            <p class="card-text"><small class="text-muted">{% for type in issue.type.all %}
                                {% if type == issue.type.last %}
                                    {{ type.title }}
                                {% else %}
                                    {{ type.title }},
                                {% endif %}
                            {% endfor %}</small></p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card-body">
                            <h5 class="card-title">{{ issue.status.title }}</h5>
                            <p class="card-text"><small class="text-muted">Updated at {{ issue.updated_at }}</small></p>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <h3>404: {{ 404_error }}</h3>
            <h3>Issues not found</h3>
        {% endfor %}
        {% if is_paginated %}
            {% include 'partial/common/paginator.html' %}
        {% endif %}
    {% endif %}
{% endblock %}

issue_tracker/templates/issue/issue_template.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1>#{{ issue.pk }} {{ issue.summary }}</h1>
    <h4>{{ issue.description|default_if_none:'' }}</h4>
    <p>Project: {{ issue.project.title }}</p>
    <p>Status: {{ issue.status.title }}</p>
    <p>Type:
        {% for type in issue.type.all %}
            {% if type == issue.type.last %}
                {{ type.title }}
            {% else %}
                {{ type.title }},
            {% endif %}
        {% endfor %}
    </p>
    <p>Created: {{ issue.created_at }}</p>
    <p>Updated: {{ issue.updated_at }}</p>
    <a href="{% url 'issue_tracker:issue_list' %}" class="btn btn-dark">Issue list</a>
    {% if perms.issue_tracker.change_issue and request.user in issue.project.users.all or request.user.is_superuser %}
        <a href="{% url 'issue_tracker:edit_issue' issue.pk %}" class="btn btn-dark">Edit</a>
    {% endif %}
    {% if perms.issue_tracker.delete_issue and request.user in issue.project.users.all or request.user.is_superuser %}
        <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">Delete</button>
        {% include 'partial/common/delete_modal.html' %}
    {% endif %}

{% endblock %}