accounts/urls.py
from django.urls import path

from django.contrib.auth.views import LogoutView

from accounts.views import (
    RegisterView, LoginUserView,
    UserProfileView, UserListView,
    UserUpdateView, UserPasswordChangeView
)

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', RegisterView.as_view(), name='create'),
    path('profile/<int:pk>', UserProfileView.as_view(), name='user_profile'),
    path('users/', UserListView.as_view(), name='user_list'),
    path('user/update', UserUpdateView.as_view(), name='user_update'),
    path('user/password/change', UserPasswordChangeView.as_view(), name='user_password_change'),
]

api/urls.py
from django.urls import path

from api.views import ProjectApiView, IssueApiView

urlpatterns = [
    path('projects/<int:pk>', ProjectApiView.as_view()),
    path('issues/<int:pk>', IssueApiView.as_view()),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
    path('', include('issue_tracker.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Profile(models.Model):
    user = models.OneToOneField(
        to=get_user_model(),
        related_name='profile',
        on_delete=models.CASCADE,
        verbose_name='Profile',
    )
    avatar = models.ImageField(
        null=True,
        blank=True,
        upload_to='user_pics',
        verbose_name='Avatar',
    )
    github_link = models.URLField(
        null=True,
        blank=True,
        verbose_name='GitHub',
    )
    about_info = models.TextField(
        max_length=2000,
        null=True,
        blank=True,
        verbose_name='About info',
    )

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'
        

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django import forms

from accounts.models import Profile


class MyUserCreationForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput,
        label='Password',
        strip=False,
        required=True,
    )
    password_confirm = forms.CharField(
        widget=forms.PasswordInput,
        label='Repeat password',
        strip=False,
        required=True,
    )
    email = forms.EmailField(required=True, label='Email', widget=forms.EmailInput)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('The passwords are not the same')
        if not first_name and not last_name:
            raise forms.ValidationError('At least first name or last name must be provided')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = [
            'username',
            'password',
            'password_confirm',
            'first_name',
            'last_name',
            'email',
        ]


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(strip=False, label='Password', widget=forms.PasswordInput)
    password_confirm = forms.CharField(strip=False, label='Password confirm', widget=forms.PasswordInput)
    old_password = forms.CharField(strip=False, label='Old password', widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data['password']
        password_confirm = self.cleaned_data['password_confirm']
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Passwords confirmation error')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data['old_password']
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Incorrect old password')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['password', 'password_confirm', 'old_password']

accounts/views.py
from django.contrib.auth import login, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import redirect, resolve_url
from django.urls import reverse
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from django.contrib.auth.views import LoginView

from accounts.forms import MyUserCreationForm, UserChangeForm, ProfileChangeForm, PasswordChangeForm
from django.conf import settings


class RegisterView(CreateView):
    model = User
    template_name = 'registration/user_create.html'
    form_class = MyUserCreationForm

    def get_context_data(self, **kwargs):
        context = super(RegisterView, self).get_context_data(**kwargs)
        context['register_page'] = 'True'
        return context

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('issue_tracker:project_list')
        return next_url


class LoginUserView(LoginView):
    redirect_authenticated_user = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['login_page'] = 'True'
        return context

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        return next_url or resolve_url(settings.LOGIN_REDIRECT_URL)


class UserProfileView(LoginRequiredMixin, DetailView):
    model = get_user_model()
    template_name = 'user_profile.html'
    context_object_name = 'user_obj'
    paginate_related_by = 5
    paginate_related_orphans = 0

    def get_context_data(self, **kwargs):
        projects = self.object.projects.order_by('start_date')
        paginator = Paginator(
            projects,
            self.paginate_related_by,
            orphans=self.paginate_related_orphans
        )
        page_number = self.request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        kwargs['page_obj'] = page
        kwargs['projects'] = page.object_list
        kwargs['is_paginated'] = page.has_other_pages()
        return super().get_context_data(**kwargs)


class UserListView(PermissionRequiredMixin, ListView):
    template_name = 'user_list.html'
    model = get_user_model()
    context_object_name = 'user_list'
    permission_required = 'auth.view_user'


class UserUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'user_edit.html'
    model = get_user_model()
    context_object_name = 'user_obj'
    form_class = UserChangeForm

    def get_object(self, queryset=None):
        return self.model.objects.get(pk=self.request.user.pk)

    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
        return super(UserUpdateView, self).get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.get_profile_form()
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        response = super().form_valid(form)
        profile_form.save()
        return response

    def form_invalid(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form)
        return self.render_to_response(context)

    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
        return ProfileChangeForm(**form_kwargs)

    def get_success_url(self):
        return reverse('accounts:user_profile', kwargs={'pk': self.object.pk})


class UserPasswordChangeView(LoginRequiredMixin, UpdateView):
    template_name = 'user_password_change.html'
    model = get_user_model()
    form_class = PasswordChangeForm
    context_object_name = 'user_obj'

    def get_object(self, queryset=None):
        return self.model.objects.get(pk=self.request.user.pk)

    def get_success_url(self):
        return reverse('accounts:login')

accounts/templates/user_edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1 style="text-align: center">Edit profile</h1>
    <form action="{% url 'accounts:user_update' %}" method="post" class="text-center account-form" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'partial/user_form.html' %}
        {% include 'partial/profile_form.html' %}
        <button type="submit" class="btn btn-dark">Edit</button>
    </form>
{% endblock %}

accounts/templates/user_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1>Users</h1>
    {% for user_obj in user_list %}
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="{% url 'accounts:user_profile' user_obj.pk %}">{{ user_obj.get_full_name }}</a>
                        </h5>
                        <p class="card-text">
                            Username: {{ user_obj.username }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    {% empty %}
        <h3>Users not found</h3>
    {% endfor %}
    {% if is_paginated %}
        {% include 'partial/common/paginator.html' %}
    {% endif %}
{% endblock %}

accounts/templates/user_password_change.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1 style="text-align: center">Change password</h1>
    <form action="{% url 'accounts:user_password_change' %}" method="post" class="text-center account-form">
        {% csrf_token %}
        <div class="mb-3">
            <label for="password" class="form-label">New password:</label>
            <input class="form-control" type="password" name="{{ form.password.name }}" id="password">
        </div>
        <div class="mb-3">
            <label for="password_confirm" class="form-label">Password confirm:</label>
            <input class="form-control" type="password" name="{{ form.password_confirm.name }}" id="password_confirm">
        </div>
        <div class="mb-3">
            <label for="old_password" class="form-label">Old password:</label>
            <input class="form-control" type="password" name="{{ form.old_password.name }}" id="old_password">
        </div>
        <button type="submit" class="btn btn-dark">Submit</button>
    </form>
{% endblock %}

accounts/templates/user_profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1>Profile of {{ user_obj.get_full_name }}</h1>

    <div class="card mb-3" style="border: none">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="{{ user_obj.profile.avatar.url|default:'/uploads/user_pics/no_image.png' }}" class="img-fluid rounded-start profile-img" alt="profile image">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">Username: {{ user_obj.username }}</h5>
                    <p class="card-text">First name: {{ user_obj.first_name }}</p>
                    <p class="card-text">Last name: {{ user_obj.last_name }}</p>
                    <p class="card-text">GitHub: <a href="{{ user_obj.profile.github_link }}">{{ user_obj.profile.github_link }}</a></p>
                    <h5 class="card-text">About info: </h5>
                    <p class="card-text">{{ user_obj.profile.about_info }}</p>
                </div>
                {% if user_obj == request.user %}
                <div>
                    <a href="{% url 'accounts:user_update' %}" class="btn btn-dark">Edit</a>
                    <a href="{% url 'accounts:user_password_change' %}" class="btn btn-dark">Change password</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    <h1>Projects</h1>
    {% include 'partial/project/partial_project_list.html' %}
{% endblock %}