accounts/urls.py
from django.urls import path

from django.contrib.auth.views import LogoutView

from accounts.views import (
    RegisterView, LoginUserView,
    UserProfileView, UserListView,
    UserUpdateView, UserPasswordChangeView
)

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', RegisterView.as_view(), name='create'),
    path('profile/<int:pk>', UserProfileView.as_view(), name='user_profile'),
    path('users/', UserListView.as_view(), name='user_list'),
    path('user/update', UserUpdateView.as_view(), name='user_update'),
    path('user/password/change', UserPasswordChangeView.as_view(), name='user_password_change'),
]

api/urls.py
from django.urls import path

from api.views import ProjectApiView, IssueApiView

urlpatterns = [
    path('projects/<int:pk>', ProjectApiView.as_view()),
    path('issues/<int:pk>', IssueApiView.as_view()),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
    path('', include('issue_tracker.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

issue_tracker/urls.py
from django.urls import path

from issue_tracker.views import (
    IssueListView, DetailIssueView,
    IssueEditView, DeleteIssueView, IssueCreateView
)
from issue_tracker.views.project_views import (
    ProjectListView, ProjectView, ProjectCreateView,
    ProjectIssueCreateView, ProjectEditView, ProjectDeleteView, ProjectUsersUpdateView)

app_name = 'issue_tracker'

issue_urls = [
    path('issues/', IssueListView.as_view(), name='issue_list'),
    path('issue/create/', IssueCreateView.as_view(), name='create_issue'),
    path('issue/<int:pk>', DetailIssueView.as_view(), name='detail_issue'),
    path('issue/edit/<int:pk>', IssueEditView.as_view(), name='edit_issue'),
    path('issue/delete/<int:pk>', DeleteIssueView.as_view(), name='delete_issue'),
]

project_urls = [
    path('', ProjectListView.as_view(), name='project_list'),
    path('project/<int:pk>', ProjectView.as_view(), name='project_detail'),
    path('project/create/', ProjectCreateView.as_view(), name='project_create'),
    path('project/<int:pk>/edit/', ProjectEditView.as_view(), name='project_edit'),
    path('project/<int:pk>/users/edit/', ProjectUsersUpdateView.as_view(), name='project_users_update'),
    path('project/<int:pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),
    path('project/<int:pk>/issue/create/', ProjectIssueCreateView.as_view(), name='project_issue_create'),
]

urlpatterns = issue_urls + project_urls

issue_tracker/forms.py
from django import forms

from issue_tracker.models import Issue, Project


class ProjectModelForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'description', 'start_date', 'end_date']


class ProjectUsersModelForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['users']


class IssueModelForm(forms.ModelForm):
    class Meta:
        model = Issue
        fields = ['project', 'summary', 'description', 'status', 'type']


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label="Search")

issue_tracker/views.py
from urllib.parse import urlencode

from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.generic import TemplateView, FormView, ListView
from issue_tracker.forms import IssueModelForm, SimpleSearchForm
from issue_tracker.models import Issue


class IndexView(ListView):
    template_name = 'issue/index.html'
    context_object_name = 'issues'
    model = Issue
    paginate_by = 5
    allow_empty = False

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        try:
            return super().get(request, *args, **kwargs)
        except Http404:
            context = {
                '404_error': 'Oops something went wrong!',
                'form': self.form
            }
            if self.search_value:
                context['query'] = urlencode({'search': self.search_value})
            return render(request, 'issue/index.html', context=context)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class IssueCreateView(FormView):
    template_name = 'issue/create_issue.html'
    form_class = IssueModelForm

    def form_valid(self, form):
        summary = form.cleaned_data['summary']
        description = form.cleaned_data['description']
        status = form.cleaned_data['status']
        types = form.cleaned_data['type']
        self.issue = Issue.objects.create(
            summary=summary,
            description=description,
            status=status
        )
        self.issue.type.set(types)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('detail_issue', kwargs={'pk': self.issue.pk})


class DetailIssueView(TemplateView):
    template_name = 'issue/issue_template.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['issue'] = get_object_or_404(Issue, pk=kwargs['pk'])
        return context


class IssueEditView(FormView):
    template_name = 'issue/edit_issue.html'
    form_class = IssueModelForm

    def dispatch(self, request, *args, **kwargs):
        self.issue = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['issue'] = self.issue
        return context

    def get_initial(self):
        initial = {}
        for key in 'summary', 'description', 'status':
            initial[key] = getattr(self.issue, key)
        initial['type'] = self.issue.type.all()
        return initial

    def form_valid(self, form):
        types = form.cleaned_data.pop('type')
        for key, value in form.cleaned_data.items():
            if value is not None:
                setattr(self.issue, key, value)
        self.issue.save()
        self.issue.type.set(types)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('detail_issue', kwargs={'pk': self.issue.pk})

    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Issue, pk=pk)


class DeleteIssueView(TemplateView):
    def post(self, request, *args, **kwargs):
        issue = get_object_or_404(Issue, pk=kwargs['pk'])
        issue.delete()
        return redirect('index')

issue_tracker/views/issue_views.py
from urllib.parse import urlencode

from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.generic import TemplateView, ListView, DeleteView, UpdateView, CreateView
from django.contrib.auth.mixins import PermissionRequiredMixin

from issue_tracker.forms import IssueModelForm, SimpleSearchForm
from issue_tracker.models import Issue


class IssueListView(ListView):
    template_name = 'issue/issue_list.html'
    context_object_name = 'issues'
    model = Issue
    paginate_by = 5
    allow_empty = False

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        try:
            return super().get(request, *args, **kwargs)
        except Http404:
            context = {
                '404_error': 'Oops something went wrong!',
                'form': self.form
            }
            if self.search_value:
                context['query'] = urlencode({'search': self.search_value})
            return render(request, 'issue/issue_list.html', context=context)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class IssueCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'issue/create_issue.html'
    form_class = IssueModelForm
    permission_required = 'issue_tracker.add_issue'

    def has_permission(self):
        return self.request.user.is_superuser

    def get_success_url(self):
        return reverse('issue_tracker:detail_issue', kwargs={'pk': self.object.pk})


class DetailIssueView(TemplateView):
    template_name = 'issue/issue_template.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['issue'] = get_object_or_404(Issue, pk=kwargs['pk'])
        return context


class IssueEditView(PermissionRequiredMixin, UpdateView):
    template_name = 'issue/edit_issue.html'
    model = Issue
    form_class = IssueModelForm
    context_object_name = 'issue'
    permission_required = 'issue_tracker.change_issue'

    def has_permission(self):
        issue = get_object_or_404(Issue, pk=self.kwargs.get('pk'))
        project = issue.project
        return (
                (super().has_permission() and (self.request.user in project.users.all())) or
                self.request.user.is_superuser
        )

    def get_success_url(self):
        return reverse('issue_tracker:detail_issue', kwargs={'pk': self.object.pk})


class DeleteIssueView(PermissionRequiredMixin, DeleteView):
    template_name = 'issue/issue_template.html'
    model = Issue
    permission_required = 'issue_tracker.delete_issue'

    def has_permission(self):
        issue = get_object_or_404(Issue, pk=self.kwargs.get('pk'))
        project = issue.project
        return (
                (super().has_permission() and (self.request.user in project.users.all())) or
                self.request.user.is_superuser
        )

    def get_success_url(self):
        return reverse('issue_tracker:project_detail', kwargs={'pk': self.object.project.pk})

issue_tracker/views/project_views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin

from issue_tracker.forms import ProjectModelForm, IssueModelForm, ProjectUsersModelForm
from issue_tracker.models import Project, Issue


class ProjectListView(ListView):
    template_name = 'project/project_list.html'
    model = Project
    context_object_name = 'projects'


class ProjectView(DetailView):
    template_name = 'project/project_detail.html'
    model = Project
    context_object_name = 'project'


class ProjectCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'project/project_create.html'
    model = Project
    form_class = ProjectModelForm
    permission_required = 'issue_tracker.add_project'

    def form_valid(self, form):
        self.object = form.save()
        self.object.users.add(self.request.user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse('issue_tracker:project_detail', kwargs={'pk': self.object.pk})


class ProjectUsersUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'project/project_users_update.html'
    model = Project
    form_class = ProjectUsersModelForm
    context_object_name = 'project'
    permission_required = 'issue_tracker.change_project_users'

    def has_permission(self):
        return (
                (super().has_permission() and (self.request.user in self.get_object().users.all())) or
                self.request.user.is_superuser
        )

    def get_success_url(self):
        return reverse('issue_tracker:project_detail', kwargs={'pk': self.object.pk})


class ProjectIssueCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'project/project_issue_create.html'
    model = Issue
    form_class = IssueModelForm
    permission_required = 'issue_tracker.add_issue'

    def has_permission(self):
        project = get_object_or_404(Project, pk=self.kwargs.get('pk'))
        return (
                (super().has_permission() and (self.request.user in project.users.all())) or
                self.request.user.is_superuser
        )

    def form_valid(self, form):
        project = get_object_or_404(Project, pk=self.kwargs.get('pk'))
        issue = form.save(commit=False)
        issue.project = project
        issue.save()
        return redirect('issue_tracker:project_detail', pk=project.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['project'] = get_object_or_404(Project, pk=self.kwargs['pk'])
        return context


class ProjectEditView(PermissionRequiredMixin, UpdateView):
    template_name = 'project/project_edit.html'
    model = Project
    form_class = ProjectModelForm
    context_object_name = 'project'
    permission_required = 'issue_tracker.change_project'

    def get_success_url(self):
        return reverse('issue_tracker:project_detail', kwargs={'pk': self.object.pk})


class ProjectDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'project/project_detail.html'
    model = Project
    success_url = reverse_lazy('issue_tracker:project_list')
    context_object_name = ''
    permission_required = 'issue_tracker.delete_project'

issue_tracker/templates/project/project_create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Create project</h1>
<form action="{% url 'issue_tracker:project_create' %}" method="post">
  {% include 'partial/common/project_form.html' with btn_title='Create' %}
  </form>
{% endblock %}

issue_tracker/templates/project/project_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1>#{{ project.pk }} {{ project.title }}</h1>
    <h4>{{ project.description|default_if_none:'' }}</h4>
    <p>Start date: {{ project.start_date }}</p>
    <p>End date: {{ project.end_date|default_if_none:'Not set' }}</p>
    <p class="users-block">Users:
        {% for user in project.users.all %}
            {% if user == project.users.last %}
                <a href="{% url 'accounts:user_profile' user.pk %}">{{ user.get_full_name }}</a>
            {% else %}
                <a href="{% url 'accounts:user_profile' user.pk %}">{{ user.get_full_name }}</a>,
            {% endif %}
        {% empty %}
            No users
        {% endfor %}
    </p>
    <a href="{% url 'issue_tracker:project_list' %}" class="btn btn-dark">Project list</a>
    {% if perms.issue_tracker.add_issue and request.user in project.users.all or request.user.is_superuser %}
        <a href="{% url 'issue_tracker:project_issue_create' project.pk %}" class="btn btn-dark">Create project
            issue</a>
    {% endif %}
    {% if perms.issue_tracker.change_project %}
        <a href="{% url 'issue_tracker:project_edit' project.pk %}" class="btn btn-dark">Edit project</a>
    {% endif %}
    {% if perms.issue_tracker.change_project_users and request.user in project.users.all or request.user.is_superuser %}
        <a href="{% url 'issue_tracker:project_users_update' project.pk %}" class="btn btn-dark">Manage users</a>
    {% endif %}
    {% if perms.issue_tracker.delete_project %}
        <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">Delete</button>
        {% include 'partial/common/delete_project_modal.html' %}
    {% endif %}
    <h1>Issues</h1>
    {% for issue in project.issues.all %}
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title"><a href="{% url 'issue_tracker:detail_issue' issue.pk %}"> {{ issue.summary }}</a></h5>
                        <p class="card-text"><small class="text-muted">#{{ issue.pk }} Created
                            at {{ issue.created_at }}</small></p>
                        <p class="card-text"><small class="text-muted">{% for type in issue.type.all %}
                            {% if type == issue.type.last %}
                                {{ type.title }}
                            {% else %}
                                {{ type.title }},
                            {% endif %}
                        {% endfor %}</small></p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card-body">
                        <h5 class="card-title">{{ issue.status.title }}</h5>
                        <p class="card-text"><small class="text-muted">Updated at {{ issue.updated_at }}</small></p>
                    </div>
                </div>
            </div>
        </div>
    {% empty %}
        <h3>The project does not have any issues</h3>
    {% endfor %}
{% endblock %}

issue_tracker/templates/project/project_edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Edit projest #{{ project.pk }}</h1>
<form action="{% url 'issue_tracker:project_edit' project.pk %}" method="post">
  {% include 'partial/common/project_form.html' with btn_title='Edit' %}
  </form>
{% endblock %}

issue_tracker/templates/project/project_issue_create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Create issue</h1>
<form action="{% url 'issue_tracker:project_issue_create' project.pk %}" method="post">
  {% include 'partial/common/project_issue_form.html' with btn_title='Create' %}
  </form>
{% endblock %}

issue_tracker/templates/project/project_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% if request.user.is_authenticated %}
        <h1>Projects</h1>
        {% include 'partial/project/partial_project_list.html' %}
    {% endif %}
{% endblock %}

issue_tracker/templates/project/project_users_update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1>Edit projest #{{ project.pk }}</h1>
    <form action="{% url 'issue_tracker:project_users_update' project.pk %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="type" class="form-label">{{ form.users.label }}</label>
            <select multiple name="{{ form.users.name }}" class="form-select" aria-label="Default select example">
                {% for choice in form.users.field.queryset %}
                    {% if choice in project.users.all %}
                        <option value="{{ choice.pk }}" selected>{{ choice.get_full_name }}</option>
                    {% else %}
                        <option value="{{ choice.pk }}">{{ choice.get_full_name }}</option>
                    {% endif %}
                {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn btn-dark">Save</button>
    </form>
{% endblock %}